services:
  database:
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - databasefiles:/var/lib/mysql
    networks:
      - main
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    restart: always

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpressfiles:/srv/www
    networks:
      - main
    env_file:
      - .env
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    ports:
      - "9000:9000"
    depends_on:
      - database
    volumes:
      - wordpressfiles:/srv/www
    networks:
      - main
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - wp_admin_username
      - wp_admin_password
      - wp_admin_email
      - wp_user_password

    restart: always

networks:
  main:
    driver: bridge
    name: main

volumes:
  wordpressfiles:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  databasefiles:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_username:
    file: ../secrets/wp_admin_username.txt